### ISSUE TITLE
program execution is stuck and cannot continue

### ISSUE THREAD

**Issue by shenhaitao010** [DeltaGroupNJUPT/Vina-GPU-2.0#11]
I have successfully compiled the Linux version of Vina-GPU+. When GPU is used, OPENCL1.2. I found that when the number of small molecules is relatively large (for example, 500), the program will be stuck and cannot continue to execute. Observe the usage of GPU. Generally, the GPU power can be used to 180W. If the program is stuck, the power will be reduced to below 100W. Is there a synchronization problem in the code that causes the program to be stuck？

**Comment by shenhaitao010** [comment]
I found that there is no similar problem with the compiled version of Windows, and I can successfully complete the task.

**Comment by xavgit** [comment]
Hi shenhaitao010,
which distribution , boost version and  Makefile BOOST_LIB_PATH setting you have used to successfully compile Vina-GPU+?
In my case with Ubuntu 22.04 , boost 1.74 and OPENCL 3 ( RTX 2080 Ti ) I receive two errors?

Thanks.
Saverio

**Comment by shenhaitao010** [comment]
Makefile setting：
BOOST_LIB_PATH=/opt/boost_1_77_0
OPENCL_LIB_PATH=/usr/local/cuda
OPENCL_VERSION=-DOPENCL_1_2
GPU_PLATFORM=-DNVIDIA_PLATFORM

I used gdb to analyze and found that the program would get stuck in the call of kernel2 function. The program is in main_ procedure_cl file :err=clEnqueueNDRangeKernel (queue, kernels [1], 2, 0, kernel2_global_size, kernel2_local_size,0, NULL, &ligands_ events[ligand_count]); checkErr(err); 

What should I do？

**Comment by shenhaitao010** [comment]
(gdb) backtrace
#0  0x00007ffff7ffa7c2 in clock_gettime ()
#1  0x00007ffff6d7aee6 in __GI___clock_gettime (clock_id=4, tp=0x7fffffffb750) at ../sysdeps/unix/clock_gettime.c:115
#2  0x00007ffff4c27c2e in ?? () from /lib64/libnvidia-opencl.so.1
#3  0x00007ffff4ccba07 in ?? () from /lib64/libnvidia-opencl.so.1
#4  0x00007ffff4c102ec in ?? () from /lib64/libnvidia-opencl.so.1
#5  0x00007ffff4c10449 in ?? () from /lib64/libnvidia-opencl.so.1
#6  0x00007ffff4ae998f in ?? () from /lib64/libnvidia-opencl.so.1
#7  0x00007ffff4afe185 in ?? () from /lib64/libnvidia-opencl.so.1
#8  0x00007ffff4afea8c in ?? () from /lib64/libnvidia-opencl.so.1
#9  0x00007ffff4aff128 in ?? () from /lib64/libnvidia-opencl.so.1
#10 0x00007ffff4af58f0 in ?? () from /lib64/libnvidia-opencl.so.1
#11 0x00007ffff4af5def in ?? () from /lib64/libnvidia-opencl.so.1
#12 0x0000000000443bf9 in main_procedure_cl (c=..., ms=..., p=..., par=..., corner1=..., corner2=..., seed=<optimized out>, outs=..., gpu_id=<optimized out>)
    at ./lib/main_procedure_cl.cpp:607
#13 0x0000000000420fa6 in main_procedure (ms=..., ref=..., out_names=..., score_only=score_only@entry=false, local_only=local_only@entry=false, 
    randomize_only=<optimized out>, no_cache=false, gd=..., exhaustiveness=1, weights=..., cpu=1, seed=-688774066, verbosity=2, num_modes=9, energy_range=3, log=..., 
    search_depth=0, thread=8000, gpu_id=2, is_docklog=0) at ./main/main.cpp:350
#14 0x000000000040d782 in main (argc=<optimized out>, argv=<optimized out>) at ./main/main.cpp:832
(gdb) frame 12
#12 0x0000000000443bf9 in main_procedure_cl (c=..., ms=..., p=..., par=..., corner1=..., corner2=..., seed=<optimized out>, outs=..., gpu_id=<optimized out>)
    at ./lib/main_procedure_cl.cpp:607
607			err = clEnqueueNDRangeKernel(queue, kernels[1], 2, 0, kernel2_global_size, kernel2_local_size,

**Comment by xavgit** [comment]
Hi shenhaitao010,
thanks for sharing your Makefile settings.
I have solved the with a newer version of Boost.
For your problem you have stated:
"I found that there is no similar problem with the compiled version of Windows, and I can successfully complete the task."
This occurs on the same machine on which there is the  program execution problem with Linux?
In this case you should check the OpenCl version on Windows as this information could help you to solve the problem.
Obviously the last word will come from the code writers.

Saverio
